# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='fav_books_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='liked_books', to='fav_books_app.User'),
        ),
    ]
